services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: prod_password
      MYSQL_DATABASE: contact_vault
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: java_migrator_prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: contact_vault
      DB_USER: root
      DB_PASSWORD: prod_password