services:
  db:
    image: mysql/mysql-server:8.0
    container_name: surya_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: contact_vault
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: surya_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_dev_data:
